[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Micro:shield"
authors = [{name = "Make and learn", email = "info@makeandlearn.cat"}]
dynamic = ["version", "description"]
